<a href="https://colab.research.google.com/github/vaishakhmohan77/Python-Assignments./blob/main/Assignment_10_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy Array Operations:
# 1. Create a 1D NumPy Array:
# Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
# 2. Inspection and Properties:
# ● Inspect the shape, data type, and the number of elements in the array. Inspect the shape of the temperatures_w1 array.

print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [4]:
# 3. Array Operations:
# ● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32
# ● Find the maximum, minimum, and mean temperatures for the week.

temperatures_w1_fahrenheit=(temperatures_w1*9/5)+32
print(temperatures_w1_fahrenheit)
print(temperatures_w1_fahrenheit.max())
print(temperatures_w1_fahrenheit.min())
print(temperatures_w1_fahrenheit.mean())

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
78.98
69.44
74.37714285714286


In [6]:
# 4. Array Slicing and Indexing:
# ● Extract the temperatures for the first three days of the week.
# ● Extract the temperatures for the weekend (last two days).
# ● Extract the temperatures for the middle three days of the week.

print(temperatures_w1_fahrenheit[:3])
print(temperatures_w1_fahrenheit[-2:])
print(temperatures_w1_fahrenheit[2:5])

[72.5  77.54 69.44]
[76.64 71.42]
[69.44 74.12 78.98]


In [9]:
# 5. Create a 2D Array:
# Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
# ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
# ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [10]:
# 6. Inspect and Slice the 2D Array:
# ● Inspect and print the shape, data type, and total number of elements in the temperatures array.
# ● Extract the temperatures for each week and the weekends (last two days) for both weeks.

print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)
print(temperatures)

(2, 7)
float64
14
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [12]:
# Pandas Series:
# 1. Creating Pandas Series:
# ● Create a Pandas Series named marks with the following data:
# ➢ Marks: 95, 92, 89, 85, 80
# ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

import pandas as pd

marks=pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [13]:
# 2. Indexing and Slicing:
# ● Use the integer index position to access the mark of the 1st rank student.
# ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
# ● Use the iloc accessor to retrieve the mark of the 3rd rank student.
# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

print(marks[0])
print(marks.loc['Rank1':'Rank3'])
print(marks.iloc[2])
print(marks[marks>90])

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_760/328145327.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [14]:
# 3. Manipulating Series:
# ● Modify the mark of the student with the 1st rank to 100.
# ● Remove the entry corresponding to the last rank from the Series.
# ● Compute the CGPA by dividing each mark in the Series by 10.

marks[0]=100
print(marks)
marks=marks.drop('Rank5')
print(marks)
print(marks/10)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


/tmp/ipykernel_760/3086366534.py:6: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[0]=100


In [15]:
# Pandas DataFrame:
# 1. Creating Pandas DataFrame:
# ● Create a Pandas DataFrame named transactions with the following data:
# ➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
# ➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
# ➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'
# ➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

transactions=pd.DataFrame({'TransactionID':[101,102,103, 104, 105, 106, 107, 108, 109, 110],
                           'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                           'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                           'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [18]:
# 2. Data Exploration:
#● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
#● Display only the 'ProductCategory' and 'Amount' columns.
#● Retrieve the last 3 columns of the DataFrame using iloc or loc.
#● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
#● Find the value counts for the 'ProductCategory' column.
#● Find the unique values in the 'Region' column.
#● Group by 'Region' and find the mean amount for each region.

print("First 5 rows (head):")
print(transactions.head())

print("\nLast 5 rows (tail):")
print(transactions.tail())

print("\nShape:", transactions.shape)
print("Column names:", transactions.columns)
print("Data types:\n", transactions.dtypes)

First 5 rows (head):
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows (tail):
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)
Column names: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
Data types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [25]:
print(transactions[['ProductCategory', 'Amount']])

print(transactions.iloc[:, -3:])

filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered)

print(transactions['ProductCategory'].value_counts())

print(transactions['Region'].unique())

print(transactions.groupby('Region')['Amount'].mean())

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
['North' 'South' 'East' 'West']
Region
East     375.0
North    287

In [29]:
# 3. Manipulating the DataFrame:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.
# ● Remove the row with TransactionID 109.
# ● Delete the 'Discount' column from the DataFrame.

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions)

transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)

transactions = transactions.drop('Discount', axis=1)
print(transactions)



   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            1

/tmp/ipykernel_760/2030982278.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transactions['Discount'] = transactions['Amount'] * 0.10
